name: 'Looker Janitor: LookML View Cleaner'
description: Tidy up Looker LookML view files by grouping, sorting and warning about inconsistencies.
author: 'Alhan Keser'

inputs:
  files:
    required: false
    type: string
    description: 'List of files to clean. If omitted, then any changed view files will be cleaned.'
    default: ''
  type_order:
    required: false
    type: string
    description: 'Order of field types.'
    default: |
      filter
      parameter
      dimension
      dimension_group
      measure
      set
  param_order:
    required: false
    type: string
    description: 'Order of field parameters.'
    default: |
      hidden
      type
      view_label
      group_label
      group_item_label
      label
      description
      sql
      sql_start
      sql_end
      value_format_name
      value_format
      filters
      drill_fields

outputs:
  warnings:
    description: 'List of warnings.'

runs:
  using: 'composite'
  steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Configure Git user
      run : |
        git config user.name github-actions
        git config user.email github-actions@github.com
      shell: bash
    - name: Checkout Looker Janitor
      uses: actions/checkout@v2
      with:
        repository: alhankeser/looker-janitor
        path: looker-janitor
        ref: main
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r looker-janitor/requirements.txt
      shell: bash
    - name: Get Changed Files
      if: ${{ inputs.files == '' }}
      id: changed_files
      uses: tj-actions/changed-files@v44
      with:
        files: |
            **.view.lkml
            **.view.lookml
    - name: Get Looker Janitor Arguments
      id: janitor_args
      run: |
        if [ "${{ inputs.files }}" != "" ]; then
          files="${{ inputs.files }}"
        else
          files="${{ steps.changed_files.outputs.all_changed_files }}"
        fi
        echo "files=${files//$'\n'/ }" >> $GITHUB_OUTPUT
        
        type_order="${{ inputs.type_order }}"
        param_order="${{ inputs.param_order }}"
        primary_key_first="${{ inputs.primary_key_first }}"
        order_by_label="${{ inputs.order_by_label }}"
        order_fields="${{ inputs.order_fields }}"
        order_field_parameters="${{ inputs.order_field_parameters }}"
        check_required_params="${{ inputs.check_required_params }}"
        required_filter="${{ inputs.required_filter }}"
        required_parameter="${{ inputs.required_parameter }}"
        required_dimension="${{ inputs.required_dimension }}"
        required_dimension_group="${{ inputs.required_dimension_group }}"
        required_measure="${{ inputs.required_measure }}"
        required_set="${{ inputs.required_set }}"

        echo "type_order=${type_order//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "param_order=${param_order//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "primary_key_first=${primary_key_first//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "order_by_label=${order_by_label//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "order_fields=${order_fields//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "order_field_parameters=${order_field_parameters//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "check_required_params=${check_required_params//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "required_filter=${required_filter//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "required_parameter=${required_parameter//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "required_dimension=${required_dimension//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "required_dimension_group=${required_dimension_group//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "required_measure=${required_measure//$'\n'/ }" >> $GITHUB_OUTPUT
        echo "required_set=${required_set//$'\n'/ }" >> $GITHUB_OUTPUT
      shell: bash
    - name: Run Looker Janitor
      id: looker_janitor
      run: |
        python looker-janitor/main.py \
        --files ${{ steps.janitor_args.outputs.files }} \
        --type_order ${{ steps.janitor_args.outputs.type_order }} \ 
        --param_order ${{ steps.janitor_args.outputs.param_order }} \ 
        --primary_key_first ${{ steps.janitor_args.outputs.primary_key_first }} \ 
        --order_by_label ${{ steps.janitor_args.outputs.order_by_label }} \ 
        --order_fields ${{ steps.janitor_args.outputs.order_fields }} \ 
        --order_field_parameters ${{ steps.janitor_args.outputs.order_field_parameters }} \ 
        --check_required_params ${{ steps.janitor_args.outputs.check_required_params }} \ 
        --required_filter ${{ steps.janitor_args.outputs.required_filter }} \ 
        --required_parameter ${{ steps.janitor_args.outputs.required_parameter }} \ 
        --required_dimension ${{ steps.janitor_args.outputs.required_dimension }} \ 
        --required_dimension_group ${{ steps.janitor_args.outputs.required_dimension_group }} \ 
        --required_measure ${{ steps.janitor_args.outputs.required_measure }} \ 
        --required_set ${{ steps.janitor_args.outputs.required_set }}
      shell: bash
    - name: Commit Cleaned Files
      id: commit_changes
      run: |
        for file in ${{ steps.janitor_args.outputs.files }}; do
            git add "${file}"
        done
        git commit -m "Run Looker Janitor" || continue
        git push
      shell: bash

branding:
  icon: check-square
  color: green
